######################################################################
# Automatically generated by qmake (2.01a) Fr. Jun 8 18:42:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../res

# Input
HEADERS += MainWindow.h DrawArea.h StateMachine.h MenuBar.h \
	../res/io.h ../res/image.h
SOURCES += main.cpp MainWindow.cpp DrawArea.cpp StateMachine.cpp \
	MenuBar.cpp \
	../res/io.cpp ../res/image.cpp
