#!/bin/sh
usage ()
{
	echo "Converts a grid into an image known by ImageMagick"
	echo "usage: $0 <outfile>"
	echo "The file ending of outfile will determine the outfile format"
}

if [ $# != 1 ]; then
	usage
	exit
else
	TODO: args io/to_tga $* | convert tga:- $1
fi
